// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
)

type Order struct {
	ID           int32         `json:"id"`
	UserID       sql.NullInt32 `json:"user_id"`
	Ispaid       bool          `json:"ispaid"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
	LastActiveAt sql.NullTime  `json:"last_active_at"`
}

type Product struct {
	ID           int32         `json:"id"`
	UserID       sql.NullInt32 `json:"user_id"`
	Price        sql.NullInt32 `json:"price"`
	Name         string        `json:"name"`
	Description  string        `json:"description"`
	Summary      string        `json:"summary"`
	Calltoaction string        `json:"calltoaction"`
	Coverimage   string        `json:"coverimage"`
	Slug         string        `json:"slug"`
	Ispablished  bool          `json:"ispablished"`
	Receipt      string        `json:"receipt"`
	Content      string        `json:"content"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
}

type User struct {
	ID           int32         `json:"id"`
	Username     string        `json:"username"`
	Name         string        `json:"name"`
	Bio          string        `json:"bio"`
	Balance      sql.NullInt32 `json:"balance"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
	LastActiveAt sql.NullTime  `json:"last_active_at"`
}
