// Code generated by sqlc. DO NOT EDIT.

package pg

import (
	"database/sql"
)

type Order struct {
	ID           int32         `json:"id"`
	UserID       sql.NullInt32 `json:"user_id"`
	Ispaid       bool          `json:"ispaid"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
	LastActiveAt sql.NullTime  `json:"last_active_at"`
}

type Product struct {
	ID           int32          `json:"id"`
	UserID       sql.NullInt32  `json:"user_id"`
	Price        sql.NullInt32  `json:"price"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	Summary      sql.NullString `json:"summary"`
	Calltoaction sql.NullString `json:"calltoaction"`
	Coverimage   sql.NullString `json:"coverimage"`
	Slug         sql.NullString `json:"slug"`
	Ispablished  bool           `json:"ispablished"`
	Receipt      sql.NullString `json:"receipt"`
	Content      sql.NullString `json:"content"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Name         string       `json:"name"`
	Bio          string       `json:"bio"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	LastActiveAt sql.NullTime `json:"last_active_at"`
}
