// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BuyProduct struct {
	ProductID int32 `json:"productId"`
}

type ExtendedUser struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
	Bio      string `json:"bio"`
	Balance  int32  `json:"balance"`
	Email    string `json:"email"`
}

type NewProduct struct {
	Name         string `json:"name"`
	Price        int32  `json:"price"`
	Description  string `json:"description"`
	Summary      string `json:"summary"`
	CallToAction string `json:"callToAction"`
	CoverImage   string `json:"coverImage"`
	Slug         string `json:"slug"`
	IsPablished  bool   `json:"isPablished"`
	Receipt      string `json:"receipt"`
	Content      string `json:"content"`
}

type PayResponse struct {
	URL string `json:"url"`
}

type PublishProduct struct {
	ProductID int32  `json:"productId"`
	Slug      string `json:"slug"`
}
